#pragma once

#define DISPLAY_WIDTH 64
#define DISPLAY_HEIGHT 32

#define EMULATOR_SCREEN_WIDTH 896
#define EMULATOR_SCREEN_HEIGHT 448


#define FPS 60
#define FRAME_TARGET_TIME (1000/FPS)

#define INSTRUCTIONS_PER_SEC 700
#define SECS_PER_INSTRUCTION 1000 / 700